import type { Metadata } from "next";
import "./globals.css";
import ClientProvider from "@/components/Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClientProvider>
        <body className={`antialiased`}>{children}</body>
      </ClientProvider>
    </html>
  );
}
